'use client'
import {useState, useEffect, useRef, useCallback} from 'react';
import Image from "next/image";
import Head from "next/head";
import AboutBanner from "@/components/AboutBanner";
import { Swiper, SwiperSlide } from "swiper/react";
import { Scrollbar } from 'swiper/modules';
import "swiper/css";

const AboutPage = () => {
    const sliderRef = useRef(null);

    const handlePrev = useCallback(() => {
        if (!sliderRef.current) return;
        sliderRef.current.swiper.slidePrev();
    }, []);

    const handleNext = useCallback(() => {
        if (!sliderRef.current) return;
        sliderRef.current.swiper.slideNext();
    }, []);


     const [offset, setOffset] = useState(0);

  const handleScroll = () => {
    const scrollPosition = window.scrollY;
    setOffset(scrollPosition * 0.1); // Adjust the multiplier to control the speed of the parallax effect
  };

  useEffect(() => {
    window.addEventListener('scroll', handleScroll);
    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);

  const [offset1, setOffset1] = useState(0);

  const handleScroll1 = () => {
    const scrollPosition1 = window.scrollY;
    setOffset1(scrollPosition1 * -0.1); // Adjust the multiplier to control the speed of the parallax effect
  };

  useEffect(() => {
    window.addEventListener('scroll', handleScroll1);
    return () => {
      window.removeEventListener('scroll', handleScroll1);
    };
  }, []);
 
  return (
    <>
      <Head>
        <title>Stance Health</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AboutBanner />
      <section className='side-img-sec sec parallaxContainer'>
        <img class="vec-grad" src="/assets/images/grad.svg" />
        <div className="container">
           <div className="row items-center">
             <div className="col-md-6">
               <div className='side-img'>
                <img style={{ transform: `translateY(${offset}px)` }} src='/assets/images/about-1-img.png' className='about-1-img' />
                <img style={{ transform: `translateY(${offset1}px)` }} src='/assets/images/about-2-img.png' className='about-2-img' />
               </div>
             </div>
             <div className="col-md-6">
               <div className='side-con'>
               <h3 className="sec-head">
               Our <span>Ethos</span>
              </h3>
              <ul>
                <li><img src="/assets/images/tick.svg" />At Stance Health, our mission is to provide high-quality care to all who aspire to have an active life. We are dedicated to redefining healthcare standards by fostering innovation in technology and using it to create patient-centered excellence in MSK care.</li>
                <li><img src="/assets/images/tick.svg" />We strive to restore function, reduce pain, and promote overall well-being by delivering exceptional and innovative physiotherapy and strengthening programs.</li>
              </ul>
               </div>
             </div>
           </div>
        </div>
      </section>
      <section className="sec test-sec">
            <div className="container">
                <div className="row">
                    <div className="col-12 text-center">
                        <h3 className="sec-head">
                        Who helps you take a <span>Stance?</span>
                        </h3>
                        <p className="para">
                        Stance is built on patient-centered care, supported by a proficient physiotherapy team that guides you through your rehab journey, addressing every aspect of your wellness. Our highly expert team comprises Physiotherapists, Strength and Conditioning Coaches, Sports Massage Therapists, and Medical and Sports Consultants.
                        </p>
                    </div>
                    <div className="col-12">
                        <div className="team-slider">
                            <Swiper
                            ref={sliderRef}
                                scrollbar={{
                                    hide: false,
                                    draggable: true,
                                }}
                                className="team-swiper"
                                modules={[Scrollbar]}
                                // autoplay={{
                                //     delay: 3000,
                                //     disableOnInteraction: false,
                                // }}
                                slidesPerView={4}
                                spaceBetween={0}
                                breakpoints={{
                                    0: {
                                        slidesPerView: 1.3,
                                        spaceBetween: 20,
                                    },
                                    640: {
                                        slidesPerView: 2,
                                        spaceBetween: 20,
                                    },
                                    768: {
                                        slidesPerView: 3,
                                        spaceBetween: 30,
                                    },
                                    1024: {
                                        slidesPerView: 4,
                                        spaceBetween: 40,
                                    },
                                }}
                                // onBeforeInit={(swiper) => {
                                // }}
                                // ref={sliderRef}
                            >
                                {/* {
                                    [...Array(5)].map((item,index)=>{
                                        return( */}
                                          <SwiperSlide>
                                                <div className="team-card">
                                                    <Image src="/assets/images/team-1.svg" width={1500} height={1500} alt="" />
                                                    <div className="con">
                                                        <div className="tp">
                                                            <h3>
                                                            Durga Joshi
                                                            </h3>
                                                            <h4>Lead Musculoskeletal and Sports Physiotherapist</h4>
                                                        </div>
                                                        <p className="para">
                                                        Durga brings over 12 years of experience in musculoskeletal and sports physiotherapy, specializing in manual therapy techniques such as Maitland, McKenzie, Clinical Pilates, and Butler’s Neurodynamic treatments. Her professional journey includes collaborations with esteemed institutions like Sakra World Hospital and YOS Sports Health Specialists, as well as working closely with industry’s best physiotherapists and sports medicine doctors.
                                                        </p>
                                                    </div>
                                                </div>
                                            </SwiperSlide>
                                            <SwiperSlide>
                                                <div className="team-card">
                                                    <Image src="/assets/images/team-2.svg" width={1500} height={1500} alt="" />
                                                    <div className="con">
                                                        <div className="tp">
                                                            <h3>
                                                            Sumesh Ashokan
                                                            </h3>
                                                            <h4>Senior Musculoskeletal and Sports Physiotherapist</h4>
                                                        </div>
                                                        <p className="para">
                                                        As an athlete turned physiotherapist, Sumesh's mission at Stance is to guide you from injury recovery to performance enhancement. With his experience in various sports and a deep understanding of human anatomy, he provides personalized care tailored to your needs. His holistic approach ensures accurate diagnosis and prevention of future injuries, helping you achieve a better tomorrow.
                                                        </p>
                                                    </div>
                                                </div>
                                            </SwiperSlide>
                                            <SwiperSlide>
                                                <div className="team-card">
                                                    <Image src="/assets/images/team-3.svg" width={1500} height={1500} alt="" />
                                                    <div className="con">
                                                        <div className="tp">
                                                            <h3>
                                                            Arjun K Raj
                                                            </h3>
                                                            <h4>Senior Strength and Conditioning Coach</h4>
                                                        </div>
                                                        <p className="para">
                                                        At Stance, Arjun's goal is to help you achieve your fitness aspirations through personalized, meticulously crafted training programs. By understanding your unique needs, he tailors each plan to guide you towards peak performance and a healthier lifestyle. Together, you will unlock your full potential and ensure every step is taken towards your success.
                                                        </p>
                                                    </div>
                                                </div>
                                            </SwiperSlide>
                                            <SwiperSlide>
                                                <div className="team-card">
                                                    <Image src="/assets/images/team-4.svg" width={1500} height={1500} alt="" />
                                                    <div className="con">
                                                        <div className="tp">
                                                            <h3>
                                                            Surbhi Paranjpe
                                                            </h3>
                                                            <h4>Senior Musculoskeletal and Sports Physiotherapist</h4>
                                                        </div>
                                                        <p className="para">
                                                        With a commitment to precise diagnosis and evidence-based treatment, Surbhi helps you manage and overcome musculoskeletal conditions. Her focus is on pain management and performance enhancement, ensuring you achieve your objectives while minimizing injury risks. Through tailored programs and education, she empowers you to reach your full athletic potential.
                                                        </p>
                                                    </div>
                                                </div>
                                            </SwiperSlide>
                                        {/* )
                                    })
                                } */}
                            </Swiper>
                            <div className="tech-nav">
                                <button className='tech-prev' onClick={handlePrev}>
                                    <Image src="/assets/images/prev.svg" width={50} height={50} />
                                </button>
                                <button className='tech-next' onClick={handleNext}>
                                    <Image src="/assets/images/next.svg" width={50} height={50} />
                                </button>
                            </div>
                        </div>

                            
                    </div>
                </div>
            </div>
        </section>

    </>
  )
}

export default AboutPage