"use client";
import Image from "next/image";
import Link from "next/link";
import Head from "next/head";
import CouponBanner from "@/components/CouponBanner";
import "swiper/css";
import CouponForm from "@/components/CouponForm";

const CouponPage = () => {
  return (
    <>
      <Head>
        <title>Stance Health</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CouponForm />
      <CouponBanner />
    </>
  );
};

export default CouponPage;
