"use client";
import Head from "next/head";
import CouponBanner from "@/components/CouponBanner";
import "swiper/css";

const CouponPage = () => {
  return (
    <>
      <Head>
        <title>Stance Health</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CouponBanner />
    </>
  );
};

export default CouponPage;
