"use client";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Link from "next/link";
import TechSlider from "@/components/TechSlider";
import TestimonialSlider from "@/components/TestimonialSlider";
import TeamSlider from "@/components/TeamSlider";
import Tab from "react-bootstrap/Tab";
import Tabs from "react-bootstrap/Tabs";
import BannerBottom from "@/components/BannerBottom";
import HomePageBanner from "@/components/HomePageBanner";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Stance Health</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      {/* <BannerSlider /> */}
      <HomePageBanner />
      <BannerBottom />
      {/* <section className="sec off-sec">
        <div className="container">
          <div className="row">
            <div className="col-12">
              <h3 className="sec-head text-center">
                Our offerings
              </h3>
            </div>
            <div className="col-12">
              <div className="off-grid">
                <Image src="/assets/images/dot-line.svg" width={1920} height={50} alt="" />
                <div className="off-wrap">
                  <Image src="/assets/images/tick.svg" alt="" width={24} height={24} />
                  <span>Functional Assessments</span>
                </div>
                <div className="off-wrap">
                  <Image src="/assets/images/tick.svg" alt="" width={24} height={24} />
                  <span>Physiotherapy</span>
                </div>
                <div className="off-wrap">
                  <Image src="/assets/images/tick.svg" alt="" width={24} height={24} />
                  <span>Strength</span>
                </div>
                <div className="off-wrap">
                  <Image src="/assets/images/tick.svg" alt="" width={24} height={24} />
                  <span>Sports Massage</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section> */}
      <TechSlider />
      <TestimonialSlider />
      <TeamSlider />
      {/* <section data-scroll data-scroll-css-progress="1" data-scroll-offset="10%, 100%" className="sec client-sec">
        <div className="container">
          <div className="row">
            <div className="col-12">
              <h3 className="sec-head text-center">
                Our Clients
              </h3>
            </div>
          </div>
        </div>
        <div className="rev-wrap">
          <div className="rev-slider">
            <div className="lg">
              <Image src="/assets/images/lg1.svg" alt="" width={100} height={100} />
            </div>
            <div className="lg">
              <Image src="/assets/images/lg1.svg" alt="" width={100} height={100} />
            </div>
            <div className="lg">
              <Image src="/assets/images/lg1.svg" alt="" width={100} height={100} />
            </div>
            <div className="lg">
              <Image src="/assets/images/lg1.svg" alt="" width={100} height={100} />
            </div>
            <div className="lg">
              <Image src="/assets/images/lg1.svg" alt="" width={100} height={100} />
            </div>
            <div className="lg">
              <Image src="/assets/images/lg1.svg" alt="" width={100} height={100} />
            </div>
            <div className="lg">
              <Image src="/assets/images/lg1.svg" alt="" width={100} height={100} />
            </div>
            <div className="lg">
              <Image src="/assets/images/lg1.svg" alt="" width={100} height={100} />
            </div>
            <div className="lg">
              <Image src="/assets/images/lg1.svg" alt="" width={100} height={100} />
            </div>
            <div className="lg">
              <Image src="/assets/images/lg1.svg" alt="" width={100} height={100} />
            </div>
            <div className="lg">
              <Image src="/assets/images/lg1.svg" alt="" width={100} height={100} />
            </div>
            <div className="lg">
              <Image src="/assets/images/lg1.svg" alt="" width={100} height={100} />
            </div>
          </div>
          <div className="rev-slider rev">
            <div className="lg">
              <Image src="/assets/images/lg1.svg" alt="" width={100} height={100} />
            </div>
            <div className="lg">
              <Image src="/assets/images/lg1.svg" alt="" width={100} height={100} />
            </div>
            <div className="lg">
              <Image src="/assets/images/lg1.svg" alt="" width={100} height={100} />
            </div>
            <div className="lg">
              <Image src="/assets/images/lg1.svg" alt="" width={100} height={100} />
            </div>
            <div className="lg">
              <Image src="/assets/images/lg1.svg" alt="" width={100} height={100} />
            </div>
            <div className="lg">
              <Image src="/assets/images/lg1.svg" alt="" width={100} height={100} />
            </div>
            <div className="lg">
              <Image src="/assets/images/lg1.svg" alt="" width={100} height={100} />
            </div>
            <div className="lg">
              <Image src="/assets/images/lg1.svg" alt="" width={100} height={100} />
            </div>
            <div className="lg">
              <Image src="/assets/images/lg1.svg" alt="" width={100} height={100} />
            </div>
            <div className="lg">
              <Image src="/assets/images/lg1.svg" alt="" width={100} height={100} />
            </div>
            <div className="lg">
              <Image src="/assets/images/lg1.svg" alt="" width={100} height={100} />
            </div>
            <div className="lg">
              <Image src="/assets/images/lg1.svg" alt="" width={100} height={100} />
            </div>
          </div>
        </div>
      </section> */}
      <section
        data-scroll
        data-scroll-css-progress="1"
        data-scroll-position="start, end"
        data-scroll-offset="-200%, 100%"
        className="sec prog-sec"
      >
        <div className="container">
          <div className="row">
            <div className="col-12 text-center">
              <h3 className="sec-head text-center">
                Programs Built <span>for you</span>
              </h3>
              <p className="para sub-txt">Tailored to fit your journey</p>
            </div>
            <div className="col-12 mt-5">
              <Tabs
                defaultActiveKey="home"
                id="uncontrolled-tab-example"
                className="mb-3 cc-tabs"
              >
                <Tab eventKey="home" title="In Your Stride">
                  <div className="row flex-lg-row-reverse pr-sec pb-0">
                    <div className="col-lg-5 col-12 ">
                      <div className="prog-con">
                        <h3 className="sec-head">
                          In Your <span>Stride</span>
                        </h3>
                        <p className="para">
                          Extensive running program designed for grassroot and
                          elite runners. Backed by high-end technology-based
                          analysis to improve your running efficiency., Our
                          approach focuses on minimizing injuries and maximizing
                          performance.
                        </p>
                        <Link href="/running" className="main-btn">
                          <span>View Program</span>
                        </Link>
                      </div>
                    </div>
                    <div className="col-lg-6 col-12 offset-lg-1">
                      <div className="prog-img">
                        <Image
                          src="/assets/images/pt-1.svg"
                          alt=""
                          width={1200}
                          height={1200}
                        />
                      </div>
                    </div>
                  </div>
                </Tab>
                <Tab eventKey="profile" title="Reclaim your Game">
                  <div className="row flex-lg-row-reverse pr-sec pb-0">
                    <div className="col-lg-5 col-12 ">
                      <div className="prog-con">
                        <h3 className="sec-head">
                          Reclaim your <span>Game</span>
                        </h3>
                        <p className="para">
                          Specialized return to sports rehab programs designed
                          to support athletes at every step of their journey.
                          Using comprehensive assessments by skilled
                          professionals, we build unique programs to bridge the
                          gap between your temporary setbacks and a full-fledged
                          comeback.
                        </p>
                        <Link href="/back-to-sports" className="main-btn">
                          <span>View Program</span>
                        </Link>
                      </div>
                    </div>
                    <div className="col-lg-6 col-12 offset-lg-1">
                      <div className="prog-img">
                        <Image
                          src="/assets/images/pt-2.svg"
                          alt=""
                          width={1200}
                          height={1200}
                        />
                      </div>
                    </div>
                  </div>
                </Tab>
                <Tab eventKey="contact" title="Back on your feet">
                  <div className="row flex-lg-row-reverse pr-sec pb-0">
                    <div className="col-lg-5 col-12 ">
                      <div className="prog-con">
                        <h3 className="sec-head">
                          Back on your <span>feet</span>
                        </h3>
                        <p className="para">
                          Stance's pre and post-operative rehab programs are
                          structured to help individuals resume activity. Both
                          programs significantly enhance outcomes. Our program
                          combines a milestone-based approach, manual
                          techniques, exercises, and tailored interventions to
                          address individual needs for each surgery type.
                        </p>
                        <Link href="/surgical-rehab" className="main-btn">
                          <span>View Program</span>
                        </Link>
                      </div>
                    </div>
                    <div className="col-lg-6 col-12 offset-lg-1">
                      <div className="prog-img">
                        <Image
                          src="/assets/images/pt-3.svg"
                          alt=""
                          width={1200}
                          height={1200}
                        />
                      </div>
                    </div>
                  </div>
                </Tab>
                <Tab eventKey="4" title="Prevention & Recovery">
                  <div className="row flex-lg-row-reverse pr-sec pb-0">
                    <div className="col-lg-5 col-12 ">
                      <div className="prog-con">
                        <h3 className="sec-head">
                          Prevention & <span>Recovery</span>
                        </h3>
                        <p className="para">
                          At Stance, we use advanced tools that provide
                          objective data on strength and functional movement
                          discrepancies, enabling us to tailor precise plans for
                          injury management and prevention. Programs are built
                          to minimize risk of injury, pain, and surgical
                          interventions.
                        </p>
                        <Link href="/injury-management" className="main-btn">
                          <span>View Program</span>
                        </Link>
                      </div>
                    </div>
                    <div className="col-lg-6 col-12 offset-lg-1">
                      <div className="prog-img">
                        <Image
                          src="/assets/images/pt-4.svg"
                          alt=""
                          width={1200}
                          height={1200}
                        />
                      </div>
                    </div>
                  </div>
                </Tab>
                <Tab eventKey="5" title="Breaking Barriers">
                  <div className="row flex-lg-row-reverse pr-sec pb-0">
                    <div className="col-lg-5 col-12 ">
                      <div className="prog-con">
                        <h3 className="sec-head">
                          Breaking <span>Barriers</span>
                        </h3>
                        <p className="para">
                           At Stance, we address lifestyle disorders by
                          empowering clients to embrace an active lifestyle
                          while prioritizing their Orthopaedic Health. Our
                          multidisciplinary team of physiotherapists and
                          strength & conditioning coaches collaborate to design
                          a personalized program aimed at enhancing your overall
                          fitness.
                        </p>
                        <Link href="/performance-training" className="main-btn">
                          <span>View Program</span>
                        </Link>
                      </div>
                    </div>
                    <div className="col-lg-6 col-12 offset-lg-1">
                      <div className="prog-img">
                        <Image
                          src="/assets/images/pt-5.svg"
                          alt=""
                          width={1200}
                          height={1200}
                        />
                      </div>
                    </div>
                  </div>
                </Tab>
              </Tabs>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
