"use client";
import { useState, useEffect, useRef } from "react";
import Head from "next/head";
import PartnersBanner from "@/components/PartnersBanner";
import "swiper/css";
import Button from "react-bootstrap/Button";
import Form from "react-bootstrap/Form";
import axios from "axios";

const PartnerPage = () => {
  const sliderRef = useRef(null);

  const [offset, setOffset] = useState(0);

  const handleScroll = () => {
    const scrollPosition = window.scrollY;
    setOffset(scrollPosition * 0.1); // Adjust the multiplier to control the speed of the parallax effect
  };

  useEffect(() => {
    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  const [offset1, setOffset1] = useState(0);

  const handleScroll1 = () => {
    const scrollPosition1 = window.scrollY - 500;
    setOffset1(scrollPosition1 * -0.1); // Adjust the multiplier to control the speed of the parallax effect
  };

  useEffect(() => {
    window.addEventListener("scroll", handleScroll1);
    return () => {
      window.removeEventListener("scroll", handleScroll1);
    };
  }, []);

  const [formData, setFormData] = useState({
    name: "",
    email: "",
    phone: "",
    occupation: "",
  });

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({ ...formData, [name]: value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    try {
      // const response = await fetch('api/sendEmail', {
      //   method: 'POST',
      //   headers: { "Content-Type": "application/json", Accept: "application/json" },
      //   body: JSON.stringify(formData),

      // });
      // const res = await axios.get('/api/hello')

      const response = await axios.post(
        "/api/submitForm",
        JSON.stringify(formData),
        {
          headers: {
            "Content-Type": "application/json",
          },
        }
      );

      const responseData = await response.json();
      console.log("res", responseData);
      if (response.ok) {
        alert("Request Sent successfully");
      } else {
        alert("Error sending request: " + responseData.message);
      }
    } catch (error) {
      console.error("Error:", error);
      alert("Request Sent Successfully");
    }
  };

  return (
    <>
      <Head>
        <title>Stance Health</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PartnersBanner />
      <section className="side-img-sec sec">
        <img className="vec-grad" src="/assets/images/grad.svg" />
        <div className="container">
          <div className="row items-center">
            <div className="col-md-6">
              <div className="side-con">
                <h3 className="sec-head">
                  Building Long-Term <span>Partnerships</span>
                </h3>
                <ul>
                  <li>
                    <img src="/assets/images/tick.svg" />
                    <span>
                      <b>Medical Professionals:</b> We specialize in elevating
                      services for Orthopedic Specialists, Physiotherapists &
                      Hospitals. Our focus on Assessments, Outcome -Centric
                      Treatment protocols, and At-home engagement improve
                      quality of care.
                    </span>
                  </li>
                  <li>
                    <img src="/assets/images/tick.svg" />
                    <span>
                      <b>Sports Academies and Clubs:</b> Amateur Clubs or
                      Professional - leagues, we help in ensuring athletes reach
                      their potential. Building sport specific protocols, we
                      have had experience in mentoring entire teams while also
                      focusing on individual athlete performance.
                    </span>
                  </li>
                  <li>
                    <img src="/assets/images/tick.svg" />
                    <span>
                      <b>Corporate Entities:</b> By combining in-office MSK
                      Assessments, High-Quality experts and technology-first
                      at-home solutions, we ensure your employees are always
                      building themselves for a better tomorrow.
                    </span>
                  </li>
                </ul>
              </div>
            </div>
            <div className="col-md-6">
              <div className="side-img side-img-right items-center">
                <img
                  style={{ transform: `translateY(${offset}px)` }}
                  src="/assets/images/partner-image-1.png"
                />
                <img
                  style={{ transform: `translateY(${offset1}px)` }}
                  src="/assets/images/partner-image-2.png"
                />
              </div>
            </div>
          </div>
        </div>
      </section>

      <div
        className="modal fade"
        id="exampleModal"
        tabindex="-1"
        aria-labelledby="exampleModalLabel"
        aria-hidden="true"
      >
        <div className="modal-dialog modal-dialog-centered">
          <div className="modal-content">
            <div className="modal-header">
              <button
                type="button"
                className="btn-close"
                data-bs-dismiss="modal"
                aria-label="Close"
              ></button>
            </div>
            <div className="modal-body">
              <h3 className="dark">Contact Us</h3>
              <Form className="form-styles" onSubmit={handleSubmit}>
                <Form.Group className="mb-3" controlId="formBasicName">
                  <Form.Control
                    type="text"
                    placeholder="Name"
                    name="name"
                    value={formData.name}
                    onChange={handleChange}
                  />
                </Form.Group>
                <Form.Group className="mb-3" controlId="formBasicEmail">
                  <Form.Control
                    type="email"
                    placeholder="Email"
                    name="email"
                    value={formData.email}
                    onChange={handleChange}
                  />
                </Form.Group>
                <Form.Group className="mb-3" controlId="formBasicPhone">
                  <Form.Control
                    type="number"
                    placeholder="Phone no."
                    name="phone"
                    value={formData.phone}
                    onChange={handleChange}
                  />
                </Form.Group>
                <Form.Group className="mb-3" controlId="formBasicOccupation">
                  <Form.Select
                    name="occupation"
                    value={formData.occupation}
                    onChange={handleChange}
                  >
                    <option value="">Occupation</option>
                    <option value="Doctor">Doctor</option>
                    <option value="Physiotherapist">Physiotherapist</option>
                    <option value="Sports Academy">Sports Academy</option>
                    <option value="Corporate">Corporate</option>
                  </Form.Select>
                </Form.Group>
                <Button variant="primary" type="submit">
                  Submit
                </Button>
              </Form>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default PartnerPage;
