'use client'
import {useState, useEffect, useLayoutEffect, useRef, useCallback} from 'react';
import Image from "next/image";
import Link from "next/link";
import Head from "next/head";
import ProgramBanner from "@/components/ProgramBanner";
import "swiper/css";
import gsap from 'gsap';

const isMobile = () => {
  return /Mobi|Android/i.test(navigator.userAgent);
};
const ProgramPage = () => {
  const sliderRef = useRef(null);

    const handlePrev = useCallback(() => {
        if (!sliderRef.current) return;
        sliderRef.current.swiper.slidePrev();
    }, []);

    const handleNext = useCallback(() => {
        if (!sliderRef.current) return;
        sliderRef.current.swiper.slideNext();
    }, []);
  useEffect(() => {
    const items = document.querySelectorAll(".item");
    
    items.forEach((item, index) => {
        let angle = (index + 1) * 72;
        setInterval(function () {
            item.style.transform = `translateX(50%) rotate(${angle}deg)`;
            
            // Apply counter-rotation to the ball elements inside the item
            const balls = item.querySelectorAll('.ball');
            balls.forEach((ball) => {
                ball.style.transform = `rotate(${-angle}deg)`;
            });
            
            angle += 10;
        }, 500);
    });
}, []);

const [open, setOpen] = useState(1);

  useLayoutEffect(() => {
    let ctx = gsap.context(() => {
      var tl = gsap.timeline({});
      tl.to('.he-col.active .he-cards', {
        position: 'relative',
      });
      tl.to('.he-col.active .he-cards', {
        opacity: 1,
        // y: '0px'
      }, "-=0.4");
      //   lottieInstance.current = lottieAnimation?.getLottie();
    });
    return () => {
      ctx.revert();
    };
  }, [open]);

  useEffect(() => {
    const handleHover = (index) => {
      if (!isMobile()) {
        setOpen(index);
      }
    };

    const handleClick = (index) => {
      if (isMobile()) {
        setOpen(index);
      }
    };

    const cols = document.querySelectorAll('.he-col');
    cols.forEach((col, index) => {
      col.addEventListener('mouseenter', () => handleHover(index + 1));
      col.addEventListener('click', () => handleClick(index + 1));
    });

    return () => {
      cols.forEach((col) => {
        col.removeEventListener('mouseenter', () => handleHover(index + 1));
        col.removeEventListener('click', () => handleClick(index + 1));
      });
    };
  }, []);
  const swiperRef = useRef(null);
  useEffect(() => {
    if (swiperRef.current) {
      swiperRef.current.swiper.on('slideChange', () => {
        const swiperInstance = swiperRef.current.swiper;
        const slides = swiperInstance.slides;
        
        slides.forEach(slide => slide.classList.remove('active-slide'));
        slides[swiperInstance.activeIndex].classList.add('active-slide');
      });
    }
  }, []);
 
  return (
    <>
      <Head>
        <title>Stance Health</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProgramBanner />
      <section className="he-sec">
        <div className="he-cols">
          <div className={`he-col ${open === 1 ? 'active' : ''}`}>
            <Image src="/assets/images/reasses.svg" alt="" width={1200} height={1200} />
            <div className="con">
              <h3>REASSESS</h3>
              <p className="para">
              To ensure we understand the root cause
              </p>
              <div className="he-cards">
                <div className="he-card">
                  <div className="ic">
                    <span>1</span>
                  </div>
                  <h3>Technology</h3>
                  <ul>
                    <li>
                    Objective Assessments using State-of-the-art Tools
                    </li>
                    <li>
                    300+ Tests Based on conditions and symptoms
                    </li>
                  </ul>
                </div>
                <div className="he-card">
                  <div className="ic">
                    <span>2</span>
                  </div>
                  <h3>Clinical</h3>
                  <ul>
                    <li>
                    Evidence Backed Manual Techniques with therapists
                    </li>
                    <li>
                    Triaging using Technology Data and Manual Assessments
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div className={`he-col ${open === 2 ? 'active' : ''}`}>
            <Image src="/assets/images/restore.svg" alt="" width={1200} height={1200} />
            <div className="con">
              <h3>RESTORE</h3>
              <p className="para">
              Creating a path to get you back to your old self.
              </p>
              <div className="he-cards">
                <div className="he-card">
                  <div className="ic">
                    <span>1</span>
                  </div>
                  <h3>Physical Therapy</h3>
                  <ul>
                    <li>
                    Pain relief using evidence backed procedures
                    </li>
                    <li>
                    Assisted movements for maximising function
                    </li>
                  </ul>
                </div>
                <div className="he-card">
                  <div className="ic">
                    <span>2</span>
                  </div>
                  <h3>Strength & Conditioning</h3>
                  <ul>
                    <li>
                    Goal specific transition to Muscle Strengthening
                    </li>
                    <li>
                    Conditioning to prevent relapse
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div className={`he-col ${open === 3 ? 'active' : ''}`}>
            <Image src="/assets/images/reignite.svg" alt="" width={1200} height={1200} />
            <div className="con">
              <h3>REIGNITE</h3>
              <p className="para">
              Building you to reach your Goals
              </p>
              <div className="he-cards">
                <div className="he-card">
                  <div className="ic">
                    <span>1</span>
                  </div>
                  <h3>Strength & Conditioning</h3>
                  <ul>
                    <li>
                    Maximise performance with experts
                    </li>
                    <li>
                    Data backed assessments to monitor progress
                    </li>
                  </ul>
                </div>
                <div className="he-card">
                  <div className="ic">
                    <span>2</span>
                  </div>
                  <h3>At-Home</h3>
                  <ul>
                    <li>
                    Clinical Supervision at Home using Technology
                    </li>
                    <li>
                    Data Driven reports used for Doctor check-ins
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="sec pb-0 circ-sec">
        <div className="container">
          <div className="row">
            <div className="col-12">
              
            </div>
          </div>
          <div className="row justify-content-center">
            <div className="col-lg-6 col-12">
              
<div id="container">
  <div id="image-container">
    <img src="/assets/images/ava-mob.svg" alt="" className="image" />
  </div>
  <Link href="/running" className="item">
    <div className="ball ball1"></div>
  </Link>
  <Link href='/performance-training' className="item">
    <div className="ball ball2"></div>
  </Link>
  <Link href="/injury-management" className="item">
    <div className="ball ball3"></div>
  </Link>
  <Link href='/surgical-rehab' className="item">
    <div className="ball ball4"></div>
  </Link>
  <Link href='/back-to-sports' className="item">
    <div className="ball ball5"></div>
  </Link>
</div>

            </div>
            <div className='col-lg-5 offset-lg-1 col-12'>
               <div className='program-side-anim'>
                  <h2 className='sec-head'>Our <span>Program</span></h2>
                  <div className='programs-list'>
                     <div className='program-div'>
                        <div className='program-div-img'>
                           <Link href="/running"><img src='/assets/images/circ1.png' /></Link>
                        </div>
                        <div className='program-div-con'>
                        <Link href="/running"><h3>In Your Stride</h3></Link>
                          <p>Extensive running program designed for grassroot and elite runners.</p>
                        </div>
                     </div>
                     <div className='program-div'>
                        <div className='program-div-img'>
                        <Link href="/back-to-sports"><img src='/assets/images/circ5.png' /></Link>
                        </div>
                        <div className='program-div-con'>
                        <Link href="/back-to-sports"><h3>Reclaim Your Game</h3></Link>
                          <p>Specialized return to sports rehab programs designed to support athletes at every step of their journey. </p>
                        </div>
                     </div>
                     <div className='program-div'>
                        <div className='program-div-img'>
                        <Link href="/surgical-rehab"><img src='/assets/images/circ4.png' /></Link>
                        </div>
                        <div className='program-div-con'>
                        <Link href="/surgical-rehab"><h3>Back On Your Feet</h3></Link>
                          <p>Stance's pre and post-operative rehab programs are structured to help individuals resume activity. </p>
                        </div>
                     </div>
                     <div className='program-div'>
                        <div className='program-div-img'>
                        <Link href="/injury-management"><img src='/assets/images/circ3.png' /></Link>
                        </div>
                        <div className='program-div-con'>
                        <Link href="/injury-management"><h3>Prevention & Recovery</h3></Link>
                          <p>At Stance, we use advanced tools that provide objective data on strength and functional movement</p>
                        </div>
                     </div>
                     <div className='program-div'>
                        <div className='program-div-img'>
                        <Link href="/performance-training"><img src='/assets/images/circ2.png' /></Link>
                        </div>
                        <div className='program-div-con'>
                        <Link href="/performance-training"><h3>Breaking Barriers</h3></Link>
                          <p>At Stance, we address lifestyle disorders by empowering clients to embrace an active lifestyle while prioritizing their Orthopaedic Health.</p>
                        </div>
                     </div>
                     
                  </div>
               </div>
            </div>
          </div>
        </div>
      </section>
      
    </>
  )
}

export default ProgramPage