'use client'
import {useState, useEffect, useRef, useCallback} from 'react';
import Image from "next/image";
import Head from "next/head";
import { Swiper, SwiperSlide } from "swiper/react";
import { Scrollbar } from 'swiper/modules';
import "swiper/css";
import WalkthroughBanner from "@/components/Walkthrough";

const AboutPage = () => {
    const sliderRef = useRef(null);

    const handlePrev = useCallback(() => {
        if (!sliderRef.current) return;
        sliderRef.current.swiper.slidePrev();
    }, []);

    const handleNext = useCallback(() => {
        if (!sliderRef.current) return;
        sliderRef.current.swiper.slideNext();
    }, []);


     const [offset, setOffset] = useState(0);

  const handleScroll = () => {
    const scrollPosition = window.scrollY;
    setOffset(scrollPosition * 0.1); // Adjust the multiplier to control the speed of the parallax effect
  };

  useEffect(() => {
    window.addEventListener('scroll', handleScroll);
    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);

  const [offset1, setOffset1] = useState(0);

  const handleScroll1 = () => {
    const scrollPosition1 = window.scrollY;
    setOffset1(scrollPosition1 * -0.1); // Adjust the multiplier to control the speed of the parallax effect
  };

  useEffect(() => {
    window.addEventListener('scroll', handleScroll1);
    return () => {
      window.removeEventListener('scroll', handleScroll1);
    };
  }, []);
 
  return (
    <>
      <Head>
        <title>Stance Health</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WalkthroughBanner />

    </>
  )
}

export default AboutPage